---
name: kafka

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: kafka
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks: [{name: default}]
  jobs:
  - name: zookeeper
    release: zookeeper
    properties: {}
  - name: kafka
    release: kafka
    properties:
      offsets:
        topic:
          replication:
            factor: 1
      transaction:
        state:
          log:
            replication:
              factor: 1
            min:
              isr: 1
  - name: kafka-manager
    release: kafka
    properties:
      username: admin
      password: ((kafka-manager-password))

variables:
- name: kafka-manager-password
  type: password

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: bpm
  sha1: e9a8d5dc34e2100c527f98fab35507cba208cdb7
  stemcell:
    os: ubuntu-trusty
    version: "3586.7"
  url: https://s3.amazonaws.com/kafka-boshrelease/compiled-releases/bpm/bpm-0.9.0-ubuntu-trusty-3586.27-20180810-223125-206133839-20180810223132.tgz
  version: 0.9.0
- name: zookeeper
  sha1: d5a67438141ddba22acbfbb3f1bc9c759ed7ae62
  stemcell:
    os: ubuntu-trusty
    version: "3586.7"
  url: https://s3.amazonaws.com/kafka-boshrelease/compiled-releases/zookeeper/zookeeper-0.0.9-ubuntu-trusty-3586.7-20180515-225907-338782705-20180515225917.tgz
  version: 0.0.9
- name: kafka
  sha1: 17def7bc250b754133926c6986a9063d8534f462
  stemcell:
    os: ubuntu-trusty
    version: "3586.7"
  url: https://s3.amazonaws.com/kafka-boshrelease/compiled-releases/kafka/kafka-1.3.0-ubuntu-trusty-3586.7-20180516-040427-61702529-20180516040435.tgz
  version: 1.3.0
