---
name: kafka

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: kafka
  azs: [z1, z2, z3]
  instances: 1
  vm_resources:
    cpu: 2
    ram: 2048
    ephemeral_disk_size: 10240
  stemcell: default
  persistent_disk: 10240
  networks: [{name: default}]
  jobs:
  - name: zookeeper
    release: zookeeper
    properties: {}
  - name: kafka
    release: kafka
    properties:
      offsets:
        topic:
          replication:
            factor: 1
      transaction:
        state:
          log:
            replication:
              factor: 1
            min:
              isr: 1
  - name: kafka-manager
    release: kafka
    properties:
      username: admin
      password: ((kafka-manager-password))

variables:
- name: kafka-manager-password
  type: password

stemcells:
- alias: default
  os: ubuntu-trusty
  version: latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: false

releases:
- name: bpm
  sha1: 74e46b56c1e923198428f8ef096851bef8c29d63
  stemcell:
    os: ubuntu-xenial
    version: "170.25"
  url: https://s3.amazonaws.com/kafka-boshrelease/compiled-releases/bpm/bpm-1.0.2-ubuntu-xenial-170.25-20190130-041024-343577954-20190130041031.tgz
  version: 1.0.2
- name: zookeeper
  sha1: 14f34a5470d6c43c5663308dabe92167c16fc381
  stemcell:
    os: ubuntu-xenial
    version: "170.25"
  url: https://s3.amazonaws.com/kafka-boshrelease/compiled-releases/zookeeper/zookeeper-0.0.9-ubuntu-xenial-170.5-20181112-234055-046983265-20181112234105.tgz
  version: 0.0.9
- name: kafka
  sha1: 843e7e7a978504c0da820993072bc38c6761acf7
  stemcell:
    os: ubuntu-xenial
    version: "170.25"
  url: https://s3.amazonaws.com/kafka-boshrelease/compiled-releases/kafka/kafka-2.2.1-ubuntu-xenial-170.25-20190130-042415-381415788-20190130042423.tgz
  version: 2.2.1
