---
name: kafka

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: zookeeper
  azs: [z1, z2, z3]
  instances: 3
  jobs:
  - name: zookeeper
    release: zookeeper
    properties: {}
  - name: status
    release: zookeeper
    properties: {}
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: default
- name: kafka
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks: [{name: default}]
  jobs:
  - name: kafka
    release: kafka
    properties:
      offsets:
        topic:
          replication:
            factor: 1
      transaction:
        state:
          log:
            replication:
              factor: 1
            min:
              isr: 1
- name: kafka-manager
  azs: [z1, z2, z3]
  instances: 1
  vm_type: default
  stemcell: default
  persistent_disk: 10240
  networks: [{name: default}]
  jobs:
  - name: kafka-manager
    release: kafka
    properties:
      username: admin
      password: ((kafka-manager-password))
- name: sanity-test
  azs: [z1, z2, z3]
  instances: 1
  lifecycle: errand
  vm_type: default
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: sanitytest
    release: kafka

variables:
- name: kafka-manager-password
  type: password

stemcells:
- alias: default
  os: ubuntu-xenial
  version: 170.latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: true

releases:
- name: bpm
  version: "0.13.0"
  url: "https://bosh.io/d/github.com/cloudfoundry-incubator/bpm-release?v=0.13.0"
  sha1: "4b6ebfdaa467c04855528172b099e565d679e0f5"
- name: zookeeper
  version: "0.0.9"
  url: "https://bosh.io/d/github.com/cppforlife/zookeeper-release?v=0.0.9"
  sha1: "c0c7cf0111ec0941aa2243530f8d418bd892c47c"
- name: kafka
  version: "2.0.0"
  url: "https://bosh.io/d/github.com/cloudfoundry-community/kafka-boshrelease?v=2.0.0"
  sha1: "1d65874ba023b0b56afac9aa654e5eb9cd9a7385"
