---
name: kafka

addons:
- name: bpm
  jobs:
  - name: bpm
    release: bpm

instance_groups:
- name: zookeeper
  azs: [z1, z2, z3]
  instances: 3
  jobs:
  - name: zookeeper
    release: zookeeper
    properties: {}
  - name: status
    release: zookeeper
    properties: {}
  vm_resources:
    cpu: 1
    ram: 1024
    ephemeral_disk_size: 10240
  stemcell: default
  persistent_disk: 10240
  networks:
  - name: default
- name: kafka
  azs: [z1, z2, z3]
  instances: 1
  vm_resources:
    cpu: 2
    ram: 2048
    ephemeral_disk_size: 10240
  stemcell: default
  persistent_disk: 10240
  networks: [{name: default}]
  jobs:
  - name: kafka
    release: kafka
    properties:
      offsets:
        topic:
          replication:
            factor: 1
      transaction:
        state:
          log:
            replication:
              factor: 1
            min:
              isr: 1
- name: kafka-manager
  azs: [z1, z2, z3]
  instances: 1
  vm_resources:
    cpu: 1
    ram: 1024
    ephemeral_disk_size: 10240
  stemcell: default
  persistent_disk: 10240
  networks: [{name: default}]
  jobs:
  - name: kafka-manager
    release: kafka
    properties:
      username: admin
      password: ((kafka-manager-password))
- name: sanity-test
  azs: [z1, z2, z3]
  instances: 1
  lifecycle: errand
  vm_resources:
    cpu: 1
    ram: 1024
    ephemeral_disk_size: 10240
  stemcell: default
  networks: [{name: default}]
  jobs:
  - name: sanitytest
    release: kafka

variables:
- name: kafka-manager-password
  type: password

stemcells:
- alias: default
  os: ubuntu-xenial
  version: 170.latest

update:
  canaries: 1
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000
  max_in_flight: 1
  serial: true

releases:
- name: bpm
  sha1: b30a3a6c296b91e2a8ad716188d5e1fc3aedd42b
  stemcell:
    os: ubuntu-xenial
    version: "170.5"
  url: https://s3.amazonaws.com/kafka-boshrelease/compiled-releases/bpm/bpm-0.13.0-ubuntu-xenial-170.5-20181112-233615-145722839-20181112233621.tgz
  version: 0.13.0
- name: zookeeper
  sha1: 14f34a5470d6c43c5663308dabe92167c16fc381
  stemcell:
    os: ubuntu-xenial
    version: "170.5"
  url: https://s3.amazonaws.com/kafka-boshrelease/compiled-releases/zookeeper/zookeeper-0.0.9-ubuntu-xenial-170.5-20181112-234055-046983265-20181112234105.tgz
  version: 0.0.9
- name: kafka
  sha1: df0895f3adc14604023f8b3d1a82c4c525e4e9a4
  stemcell:
    os: ubuntu-xenial
    version: "170.5"
  url: https://github.com/cloudfoundry-community/kafka-boshrelease/releases/download/v2.2.0/kafka-2.2.0.tgz
  version: 2.2.0
