---
anchors:
  smarsh_releases_bucket: &smarsh_releases_bucket
    bucket: smarsh-bosh-releases
    access_key_id: ((aws-access-key-id))
    secret_access_key: ((aws-secret-access-key))
  blobstore_credentials: &blobstore_credentials
    AWS_ACCESS_KEY_ID: ((aws-access-key-id))
    AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key))
  bosh-creds: &bosh-creds
    jumpbox_key: ((jumpbox-key))
    ca_cert: ((ca-cert))
    BOSH_ENVIRONMENT: ((bosh-environment))

resource_types:
  - name: cache-file-contents
    type: docker-image
    source:
      repository: moredhel/keyval-resource
      
resources:
  - name: boshcli2
    type: registry-image
    source:
      repository: afamuzoka/boshcli2
      username: ((docker.username))
      password: ((docker.password))
      tag: latest
  
  - name: s3-rc-release
    type: s3
    source:
      << : *smarsh_releases_bucket
      regexp: sredataservices/rc-release/kafka-(.*).tgz

  - name: version
    type: semver
    source:
      driver: s3
      << : *smarsh_releases_bucket
      region: eu-west-2
      key: sredataservices/version
      initial_version: 2.4.2

  - name: kafka-repo
    type: git
    icon: github-circle
    source:
      uri: https://github.com/Smarsh/cf-kafka-boshrelease
      branch: SAAS-281
  
  - name: kafka-final-release
    type: s3
    source:
      << : *smarsh_releases_bucket
      regexp: sredataservices/release/kafka-(.*).tgz

  - name: blobs-yml
    type: cache-file-contents

jobs:

  - name: rc
    public: true
    serial: true
    plan:
      - get: kafka-repo
        trigger: true
      - get: version
        trigger: false
        params:
          pre: rc 
      - put: version
        params:
          file: version/number

  - name: create-rc-release
    public: true
    serial: true
    plan:
      - get: kafka-repo
        trigger: true
      - get: version
        trigger: false
        params:
          pre: rc 
      - put: version
        params:
          file: version/number
          
      - get: boshcli2
      - task: create-rc-release
        file: kafka-repo/ci/tasks/create-rc-release.yml 
        image: boshcli2
      - put: blobs-yml
        params:
          file: blobs-yml/blobs.yml
      - put: s3-rc-release
        params:
          file: create-rc-release/kafka-*.tgz

  - name: cut-release
    public: true
    serial: true
    plan:
      - get: kafka-repo
        trigger: false
        passed: 
          - create-rc-release
      - get: version
        trigger: false
        params:
          bump: final
        passed:
          - create-rc-release
      - get: s3-rc-release
      - get: boshcli2
      - task: create-final-release
        file: kafka-repo/ci/tasks/create-final-release.yml
        image: boshcli2
        params: 
          << : *blobstore_credentials
          << : *bosh-creds
          BLOBSTORE: smarsh-bosh-release-blobs
      - put: kafka-final-release
        params:
          file: release-tarball/kafka-*.tgz
      - name: version-bump
        put: version
        params:
          bump: patch
