---
anchors:
  smarsh_releases_bucket: &smarsh_releases_bucket
    bucket: smarsh-bosh-releases
    access_key_id: ((aws-access-key-id))
    secret_access_key: ((aws-secret-access-key))
  blobstore_credentials: &blobstore_credentials
    AWS_ACCESS_KEY_ID: ((aws-access-key-id))
    AWS_SECRET_ACCESS_KEY: ((aws-secret-access-key))
  bosh-creds: &bosh-creds
    jumpbox_key: |
      ((jumpbox-key))
    ca_cert: |
      ((ca-cert))
    BOSH_ENVIRONMENT: ((bosh-environment))
   
resources:
  - name: bosh-cli2
    type: registry-image
    source:
      repository: acuzoka/bosh-cli2
      username: ((docker.username))
      password: ((docker.password))
      tag: latest
  
  - name: s3-dev-release
    type: s3
    source:
      << : *smarsh_releases_bucket
      regexp: sredataservices/dev-releases/kafka-(.*).tgz

  - name: version
    type: semver
    source:
      driver: s3
      << : *smarsh_releases_bucket
      region: eu-west-2
      file: sredataservices/version
      initial_version: 2.4.2

  - name: kafka-repo
    type: git
    icon: github-circle
    source:
      uri: https://github.com/Smarsh/cf-kafka-boshrelease
      branch: master
  
  - name: kafka-final-release
    type: s3
    source:
      << : *smarsh_releases_bucket
      regexp: sredataservices/releases/kafka-(.*).tgz

jobs:
  - name: create-dev-release
    public: true
    serial: true
    plan:
      - get: kafka-repo
        version: every
        trigger: true
      - get: version
        trigger: false
        params:
          pre: rc
      - put: version
      # - put: version
      #   params:
      #     bump: patch
      - get: bosh-cli2
      - task: create-dev-release
        file:  kafka-repo/ci/tasks/create-dev-release.yml 
        image: bosh-cli2
        # on_failure:
          # put: pull-request
          # params:
          #   path: pull-request
          #   status: failure
      
      - put: s3-dev-release
        params:
          file: create-dev-release/kafka-*.tgz

  - name: cut-release
    public: true
    plan:
      - get: kafka-repo
        trigger: true
      - get: version
        params:
          bump: patch   
      - task: create_final_release
        file: kafka-repo/ci/tasks/create_final_release.yml
        params: 
          << : *blobstore_credentials
          << : *bosh-creds
          BLOBSTORE: smarsh-bosh-release-blobs
      - put: kafka-final-release
        params:
          file: release_tarball/kafka-*.tgz
